import type { NextConfig } from "next";

/**
 * Configure Next/Image so it will accept the URLs generated by the backend
 * (http://localhost:8080/uploads/...) and still allow any other remote images
 * we might paste into the profile form. We keep the optimization pipeline for
 * known hosts, and fall back to the built-in loader for everything else.
 */
const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "http",
        hostname: "localhost",
        port: "8080",
        pathname: "/uploads/**",
      },
      {
        protocol: "https",
        hostname: "*",
      },
      {
        protocol: "http",
        hostname: "*",
      },
    ],
  },
};

export default nextConfig;
